name: Publish

on:
  push:
    tags:
      - 'v*'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:

  publish:
    runs-on: ubuntu-latest
    container: unityci/editor:6000.0.80f1-base-3
    permissions:
      contents: write
    steps:

    - name: Checkout Package
      uses: actions/checkout@v7
      with:
        lfs: true

    - name: Restore Library from cache
      uses: actions/cache@v6
      with:
        path: Library
        key: Library-base

    - name: Activate Unity
      run: |
        echo "$UNITY_LICENSE" > /Unity_v2022.x.ulf

        unity-editor \
        -batchmode -nographics -quit -logFile - \
        -manualLicenseFile /Unity_v2022.x.ulf || true

        rm /Unity_v2022.x.ulf

    - name: Build .tgz
      id: build_tgz
      run: |
        mkdir -p Builds

        unity-editor \
        -batchmode -nographics -quit -logFile - \
        -projectPath . \
        -executeMethod PackageBuilder.PackTgz

        echo "path=$(ls Builds/*.tgz)" >> $GITHUB_OUTPUT
        echo "name=$(basename Builds/*.tgz)" >> $GITHUB_OUTPUT

    - name: Upload .tgz to artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.build_tgz.outputs.name }}
        path: ${{ steps.build_tgz.outputs.path }}
        archive: false
        retention-days: 5

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build_tgz.outputs.path }}
        artifactContentType: application/gzip
